name: ci

on: [push]

jobs:
  test:
    name: build & test
    runs-on: macos-latest
    env:
      scheme: ${{ 'SimpleHMACAuthTests' }}
      project: ${{ 'SimpleHMACAuth.xcodeproj' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: xcodebuild build-for-testing -project "$project" -scheme "$scheme"
      - name: Test
        run: xcodebuild test-without-building -project "$project" -scheme "$scheme"
